apiVersion: apps/v1
kind: Deployment
metadata:
  name: test-app
  namespace: dev-test
spec:
  replicas: 1
  selector:
    matchLabels:
      app: test-app
  template:
    metadata:
      labels:
        app: test-app
      annotations:
        prometheus.io/scrape: 'true'
        prometheus.io/path: '/metrics'
        prometheus.io/port: '8080'
    spec:
      containers:
      - name: test-app
        image: busybox:latest
        command: ['sleep', '3600']
        ports:
        - containerPort: 8080
          name: metrics
