apiVersion: apps/v1
kind: Deployment
metadata:
  name: api-app
  namespace: prod-api
spec:
  replicas: 3
  selector:
    matchLabels:
      app: api-app
  template:
    metadata:
      labels:
        app: api-app
      annotations:
        prometheus.io/scrape: 'true'
        prometheus.io/path: '/actuator/prometheus'
        prometheus.io/port: '9090'
    spec:
      containers:
      - name: api-app
        image: httpd:latest
        ports:
        - containerPort: 80
        - containerPort: 9090
          name: metrics
---
apiVersion: v1
kind: Service
metadata:
  name: api-service
  namespace: prod-api
spec:
  selector:
    app: api-app
  ports:
  - port: 80
    targetPort: 80
    name: http
  - port: 9090
    targetPort: 9090
    name: metrics
